### ISSUE TITLE
Wallet view Covalent API use for - Astar - Shibuya has been sunsetted. Figure out a new API to use for Astar - Shibuya

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex-evm#27]
Need to fix this;

<img width="1829" alt="image" src="https://github.com/Itheum/data-dex-evm/assets/743169/0d9e785a-5055-49aa-a4ea-0420ba3dea3d">

**Comment by newbreedofgeek** [comment]
@911-Benedek-RobertGeorge could we swap out the Covalent API with the Bluz API we are using in the marketplace? is that possible? here are the bluz endpoint - https://shibuya.api.bluez.app/api/

**Comment by damienen** [comment]
Closing it for now
