### ISSUE TITLE
Reloading any route, goes to the /home route

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex-evm#3]
**Current Behaviour:**
1. Login and you get sent to the "/home" route
2. Reload the page and it remains in the "/home" route. This is correct
3. Go to "wallet" and the route changes to "/datanfts/wallet" route.
4. Reload the page, and it goes back to "/home" route

**Expected Behaviour:**
In step 4 above, when you reload - it should remain in the "/datanfts/wallet" route with the user still logged in. This should also be the case for other routes like "/datanfts/marketplace/market"

**Comment by damienen** [comment]
@newbreedofgeek please check this whenever you have time

**Comment by newbreedofgeek** [comment]
good
